[package]
name = "rust-bsa-extract"
description = "Tool to extract Bethesda Softworks Archives (BSAs)"
license = "MIT"
version = "0.1.2"
authors = ["dangreco <dan.greco@live.com>"]

[dependencies]
byteorder = "1.2.6"
pbr = "1.0.1"
